import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <nav>
                    <img src="" alt="" srcSet="" />
                    <a href="/">Home</a>
                    <a href="/events">Events</a>
                    <a href="/about">About us</a>
                </nav>
            </header>
            <main className={styles.main}>
                <h2> Events in London</h2>
                <p>
                    {" "}
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Ipsam saepe quasi, harum nisi autem eaque exercitationem
                    quis, atque laboriosam nulla quae, et dicta aliquid quas
                    cupiditate fugit tenetur maxime ipsum.
                </p>
                <a href="http://">
                    <img  />
                </a>
                <h2> Events in Sanfransicco</h2>
                <p>
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                    Est dolor repellat fugit modi enim facere commodi id!
                    Tempora eum consequatur quas quisquam numquam est veritatis
                    quaerat ex eligendi? Architecto, deleniti!
                </p>
                <a href="http://">
                    <img  />
                </a>
                <h2> Events in Barcelona</h2>
                <p> lor
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Velit, sint. Harum laborum expedita beatae doloribus,
                    provident animi architecto. Ea omnis possimus repellendus
                    beatae eum ullam, voluptatem molestias distinctio architecto
                    praesentium.
                </p>
                <a href="http://">
                    <img  />
                </a>
            </main>
            <footer className={styles.footer}>footer</footer>
        </>
    );
}
